Ariel Choquetopa - Add song lyrucs
git-training-branch/shared pull request #7
Opened 2020-11-05 03:39 UTC by ArielPuma747

Song: warning sign
Artist: coldplay

2020-11-05 03:41 UTC, ArielPuma747 commented
@noemiguzo can you review this PR?

2020-11-06 00:36 UTC, noemiguzo requested changes

2020-11-06 00:36 UTC, noemiguzo commented on ariel-choquetopa.txt
> +A warning signal
signal es sign

2020-11-06 00:36 UTC, noemiguzo commented on ariel-choquetopa.txt
> +I've gotta tell yeah what a state I'm in
yeah es you

2020-11-06 00:36 UTC, noemiguzo commented on ariel-choquetopa.txt
> +That I started looking for a warning signed
signed es sign

2020-11-06 00:36 UTC, noemiguzo commented on ariel-choquetopa.txt
> +Yeah the truth is
falta ',' despues de Yeah

2020-11-06 00:36 UTC, noemiguzo commented on ariel-choquetopa.txt
> +I missed the good part, then You realized
quitar ','
You realized es 'I realised'

2020-11-06 03:03 UTC, ArielPuma747 commented on ariel-choquetopa.txt
> +A warning signal
Done

2020-11-06 03:03 UTC, ArielPuma747 commented on ariel-choquetopa.txt
> +I've gotta tell yeah what a state I'm in
Done

2020-11-06 03:03 UTC, ArielPuma747 commented on ariel-choquetopa.txt
> +That I started looking for a warning signed
Done

2020-11-06 03:03 UTC, ArielPuma747 commented on ariel-choquetopa.txt
> +Yeah the truth is
Done

2020-11-06 03:03 UTC, ArielPuma747 commented on ariel-choquetopa.txt
> +I missed the good part, then You realized
Done

2020-11-06 03:04 UTC, ArielPuma747 commented
@noemiguzo can you review this PR? is updated with your observation

2020-11-06 13:29 UTC, noemiguzo approved these changes

2020-11-06 13:29 UTC, noemiguzo commented
Approved

2020-11-06 18:17 UTC, merged